### ISSUE TITLE
最新的go-stash docker镜像启动不了

### ISSUE THREAD

**Issue by gif-gif** [kevwan/go-stash#61]
docker-compose启动：
```
  go-stash:
    image: kevinwan/go-stash:latest  # if you "macOs intel" or "linux amd"
    container_name: go-stash
    environment:
      # 时区上海 - Time zone Shanghai (Change if needed)
      TZ: Asia/Shanghai
    user: root
    restart: always
```
linux centos 报错
```
Error response from daemon: unable to find user root: no matching entries in passwd file
```
